<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ComeetAutomationProject"
           tests="6"
           failures="4"
           errors="0"
           skipped="0"
           time="16.105">
    <properties></properties>

            <testcase
                name="validLogin_WithoutRememberMe"
                time="1.000"
                classname="LoginTests">

            <failure type="java.lang.AssertionError" message="Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]">
                <![CDATA[java.lang.AssertionError: Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]
                org.testng.Assert.fail(Assert.java:94)org.testng.Assert.failNotEquals(Assert.java:513)org.testng.Assert.assertEqualsImpl(Assert.java:135)org.testng.Assert.assertEquals(Assert.java:116)org.testng.Assert.assertEquals(Assert.java:190)LoginTests.validLogin_WithoutRememberMe(LoginTests.java:63)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)org.testng.internal.Invoker.invokeMethod(Invoker.java:645)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)org.testng.TestRunner.privateRun(TestRunner.java:756)org.testng.TestRunner.run(TestRunner.java:610)org.testng.SuiteRunner.runTest(SuiteRunner.java:387)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)org.testng.TestNG.runSuitesLocally(TestNG.java:1218)org.testng.TestNG.runSuites(TestNG.java:1133)org.testng.TestNG.run(TestNG.java:1104)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>
            <testcase
                name="validLogin_WithRememberMe"
                time="1.069"
                classname="LoginTests">

            <failure type="java.lang.AssertionError" message="Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]">
                <![CDATA[java.lang.AssertionError: Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]
                org.testng.Assert.fail(Assert.java:94)org.testng.Assert.failNotEquals(Assert.java:513)org.testng.Assert.assertEqualsImpl(Assert.java:135)org.testng.Assert.assertEquals(Assert.java:116)org.testng.Assert.assertEquals(Assert.java:190)LoginTests.validLogin_WithRememberMe(LoginTests.java:40)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)org.testng.internal.Invoker.invokeMethod(Invoker.java:645)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)org.testng.TestRunner.privateRun(TestRunner.java:756)org.testng.TestRunner.run(TestRunner.java:610)org.testng.SuiteRunner.runTest(SuiteRunner.java:387)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)org.testng.TestNG.runSuitesLocally(TestNG.java:1218)org.testng.TestNG.runSuites(TestNG.java:1133)org.testng.TestNG.run(TestNG.java:1104)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>
            <testcase
                name="validLogin_WithRememberMe"
                time="1.054"
                classname="LoginTests">

            <failure type="java.lang.AssertionError" message="Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]">
                <![CDATA[java.lang.AssertionError: Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]
                org.testng.Assert.fail(Assert.java:94)org.testng.Assert.failNotEquals(Assert.java:513)org.testng.Assert.assertEqualsImpl(Assert.java:135)org.testng.Assert.assertEquals(Assert.java:116)org.testng.Assert.assertEquals(Assert.java:190)LoginTests.validLogin_WithRememberMe(LoginTests.java:40)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)org.testng.internal.Invoker.invokeMethod(Invoker.java:645)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)org.testng.TestRunner.privateRun(TestRunner.java:756)org.testng.TestRunner.run(TestRunner.java:610)org.testng.SuiteRunner.runTest(SuiteRunner.java:387)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)org.testng.TestNG.runSuitesLocally(TestNG.java:1218)org.testng.TestNG.runSuites(TestNG.java:1133)org.testng.TestNG.run(TestNG.java:1104)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>
            <testcase
                name="validLogin_WithoutRememberMe"
                time="1.015"
                classname="LoginTests">

            <failure type="java.lang.AssertionError" message="Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]">
                <![CDATA[java.lang.AssertionError: Login was unsuccessful expected [https://bootsnipp.com/user] but found [https://bootsnipp.com/login]
                org.testng.Assert.fail(Assert.java:94)org.testng.Assert.failNotEquals(Assert.java:513)org.testng.Assert.assertEqualsImpl(Assert.java:135)org.testng.Assert.assertEquals(Assert.java:116)org.testng.Assert.assertEquals(Assert.java:190)LoginTests.validLogin_WithoutRememberMe(LoginTests.java:63)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:567)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)org.testng.internal.Invoker.invokeMethod(Invoker.java:645)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)org.testng.TestRunner.privateRun(TestRunner.java:756)org.testng.TestRunner.run(TestRunner.java:610)org.testng.SuiteRunner.runTest(SuiteRunner.java:387)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)org.testng.SuiteRunner.run(SuiteRunner.java:289)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)org.testng.TestNG.runSuitesLocally(TestNG.java:1218)org.testng.TestNG.runSuites(TestNG.java:1133)org.testng.TestNG.run(TestNG.java:1104)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


            <testcase
                name="validLogin_WithRememberMe"
                time="5.861"
                classname="LoginTests">
            </testcase>
            <testcase
                name="validLogin_WithoutRememberMe"
                time="6.106"
                classname="LoginTests">
            </testcase>
</testsuite>
